// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import { IEntropyConsumer } from "@pythnetwork/entropy-sdk-solidity/IEntropyConsumer.sol";
import { IEntropyV2 } from "@pythnetwork/entropy-sdk-solidity/IEntropyV2.sol";

/**
 * @title EntropyWallet
 * @dev Simple smart contract that uses Pyth Network entropy to generate secure wallet addresses
 * @notice This contract implements IEntropyConsumer to receive random numbers from Pyth Network
 */
contract EntropyWallet is IEntropyConsumer {
    
    // Pyth Entropy contract interface
    IEntropyV2 public immutable entropy;
    
    // Mapping to store generated wallets by sequence number
    mapping(uint64 => address) public generatedWallets;
    
    // Mapping to store who requested each sequence number
    mapping(uint64 => address) public requesters;
    
    // Event emitted when a wallet is generated
    event WalletGenerated(uint64 indexed sequenceNumber, address indexed requester, address walletAddress);
    
    // Event emitted when randomness is requested
    event RandomnessRequested(uint64 indexed sequenceNumber, address indexed requester);
    
    /**
     * @dev Constructor sets the Pyth Entropy contract address
     * @param _entropy Address of the Pyth Entropy contract on Base mainnet
     */
    constructor(address _entropy) {
        entropy = IEntropyV2(_entropy);
    }
    
    /**
     * @dev Request a random wallet generation using Pyth Network entropy
     * @notice This function requests randomness from Pyth and pays the required fee
     * @return sequenceNumber The sequence number for tracking this request
     */
    function requestRandomWallet() external payable returns (uint64) {
        // Get the fee required for entropy request
        uint256 fee = entropy.getFeeV2();
        require(msg.value >= fee, "Insufficient fee for entropy request");
        
        // Request randomness from Pyth using V2 interface
        uint64 sequenceNumber = entropy.requestV2{ value: fee }();
        
        // Store the requester
        requesters[sequenceNumber] = msg.sender;
        
        emit RandomnessRequested(sequenceNumber, msg.sender);
        
        // Refund excess payment
        if (msg.value > fee) {
            payable(msg.sender).transfer(msg.value - fee);
        }
        
        return sequenceNumber;
    }
    
    /**
     * @dev Callback function called by Pyth Entropy contract with random number
     * @param sequenceNumber The sequence number of the request
     * @param provider The address of the provider that generated the random number
     * @param randomNumber The random number generated by Pyth Network
     */
    function entropyCallback(
        uint64 sequenceNumber,
        address provider,
        bytes32 randomNumber
    ) internal override {
        // Generate a deterministic wallet address from the random number
        address walletAddress = generateWalletAddress(randomNumber);
        
        // Store the generated wallet
        generatedWallets[sequenceNumber] = walletAddress;
        
        emit WalletGenerated(sequenceNumber, requesters[sequenceNumber], walletAddress);
    }
    
    /**
     * @dev Generate a wallet address from random bytes
     * @param randomBytes The random bytes from Pyth Network
     * @return walletAddress The generated wallet address
     */
    function generateWalletAddress(bytes32 randomBytes) public pure returns (address) {
        // Use the random bytes as a private key to derive the public address
        // This creates a deterministic wallet address from the entropy
        return address(uint160(uint256(keccak256(abi.encodePacked(randomBytes)))));
    }
    
    /**
     * @dev Get the wallet address for a given sequence number
     * @param sequenceNumber The sequence number to check
     * @return The generated wallet address (zero if not yet generated)
     */
    function getWallet(uint64 sequenceNumber) external view returns (address) {
        return generatedWallets[sequenceNumber];
    }
    
    /**
     * @dev Get the requester for a given sequence number
     * @param sequenceNumber The sequence number to check
     * @return The address that requested this wallet generation
     */
    function getRequester(uint64 sequenceNumber) external view returns (address) {
        return requesters[sequenceNumber];
    }
    
    /**
     * @dev Get the current fee for requesting entropy
     * @return The fee amount in wei
     */
    function getEntropyFee() external view returns (uint256) {
        return entropy.getFeeV2();
    }
    
    /**
     * @dev Required by IEntropyConsumer - returns the entropy contract address
     * @return Address of the entropy contract
     */
    function getEntropy() internal view override returns (address) {
        return address(entropy);
    }
    
    /**
     * @dev Allow contract to receive ETH
     */
    receive() external payable {}
}